#!/bin/bash
ORIGINAL_STASHED_COUNT=`git stash list | wc -l`
git stash --keep-index
NEW_STASHED_COUNT=`git stash list | wc -l`

returnvalue=0

npm test

if [[ $? -eq 1 ]]; then
  returnvalue=1
fi

# Don't allow console.log() statements to be committed.

count=`grep -iR --include \*.js 'console\.log' ./src ./test | wc -l | awk '{print $1}'`
if [[ "$count" -ne 2 ]]; then 
  remove=$count - 2
  echo "Remove $remove console.log() statements"
  returnvalue=1
fi

# Don't allow .only() statements to be committed in tests

count=`grep -iR --include \*.js '.only(' ./test | wc -l | awk '{print $1}'`
if [[ "$count" -ne 0 ]]; then 
  echo "Remove $count .only() statements from test"
  returnvalue=1
fi

if [ $NEW_STASHED_COUNT -gt $ORIGINAL_STASHED_COUNT ]
then
  git stash pop
fi

exit $returnvalue