#!/bin/bash
npm test

if [[ $? -eq 1 ]]; then
  exit 1
fi

# Don't allow console.log() statements to be committed.

count=`grep -iR --include \*.js 'console\.log' ./src ./test | wc -l | awk '{print $1}'`
if [[ "$count" -ne 1 ]]; then 
  echo "Remove $count console.log() statements"
  exit 1
fi

# Don't allow .only() statements to be committed in tests

count=`grep -iR --include \*.js '.only(' ./test | wc -l | awk '{print $1}'`
if [[ "$count" -ne 0 ]]; then 
  echo "Remove $count .only() statements from test"
  exit 1
fi
